# ==============================================================================
#  Fluxe POS Server — Windows Auto-Start Setup
#  Run once as Administrator on each kiosk machine.
#
#  What this does:
#    1. Verifica Node.js instalado
#    2. Instala dependencias (npm install) se necessario
#    3. Cria launcher oculto (sem janela de terminal)
#    4. Registra tarefa no Task Scheduler para subir no login
#    5. Inicia o servidor imediatamente
#
#  Para remover: schtasks /delete /tn "FluxePOSServer" /f
# ==============================================================================

#Requires -RunAsAdministrator
$ErrorActionPreference = 'Stop'

$TaskName  = 'FluxePOSServer'
$ServerDir = $PSScriptRoot
$VbsPath   = Join-Path $ServerDir 'start-server-hidden.vbs'
$LogDir    = Join-Path $ServerDir 'logs'
$LogFile   = Join-Path $LogDir   'server.log'

Write-Host ""
Write-Host "  Fluxe POS Server — Auto-Start Setup" -ForegroundColor Cyan
Write-Host "  =====================================" -ForegroundColor Cyan
Write-Host ""

# ── 1. Verificar Node.js ──────────────────────────────────────────────────────
$nodePath = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $nodePath) {
    Write-Host "  ERRO: Node.js nao encontrado no PATH." -ForegroundColor Red
    Write-Host "  Instale em https://nodejs.org e rode este script novamente." -ForegroundColor Yellow
    Write-Host ""
    Read-Host "  Pressione Enter para sair"
    exit 1
}
Write-Host "  [OK] Node.js: $nodePath" -ForegroundColor Green

# ── 2. Instalar dependencias se necessario ────────────────────────────────────
$nmPath = Join-Path $ServerDir 'node_modules'
if (-not (Test-Path $nmPath)) {
    Write-Host "  Instalando dependencias (npm install)..." -ForegroundColor Yellow
    Push-Location $ServerDir
    & npm install --silent 2>&1 | Out-Null
    Pop-Location
    Write-Host "  [OK] Dependencias instaladas" -ForegroundColor Green
} else {
    Write-Host "  [OK] Dependencias ja instaladas" -ForegroundColor Green
}

# ── 3. Criar pasta de logs ────────────────────────────────────────────────────
New-Item -ItemType Directory -Path $LogDir -Force | Out-Null

# ── 4. Criar launcher VBScript (sem janela de terminal) ───────────────────────
#
#  wsh.Run com windowStyle=0 inicia o processo completamente oculto.
#  O >> redireciona stdout+stderr para server.log para debug futuro.
#
$escapedNode   = $nodePath   -replace '\\', '\\'
$escapedDir    = $ServerDir  -replace '\\', '\\'
$escapedLog    = $LogFile    -replace '\\', '\\'

$vbs = @"
' Fluxe POS Server - hidden launcher (no terminal window)
' Auto-generated by setup-autostart.ps1 — do not edit manually.
Dim wsh : Set wsh = CreateObject("WScript.Shell")
wsh.CurrentDirectory = "$escapedDir"
wsh.Run "cmd /c """"$escapedNode"""" server.js >> """"$escapedLog"""" 2>&1", 0, False
"@

Set-Content -Path $VbsPath -Value $vbs -Encoding UTF8
Write-Host "  [OK] Launcher criado: $VbsPath" -ForegroundColor Green

# ── 5. Remover tarefa anterior se existir ─────────────────────────────────────
if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Stop-ScheduledTask  -TaskName $TaskName -ErrorAction SilentlyContinue
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "  [OK] Tarefa anterior removida" -ForegroundColor Green
}

# ── 6. Registrar tarefa no Task Scheduler ────────────────────────────────────
$action   = New-ScheduledTaskAction `
    -Execute         'wscript.exe' `
    -Argument        "`"$VbsPath`"" `
    -WorkingDirectory $ServerDir

$trigger  = New-ScheduledTaskTrigger -AtLogOn

$settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -RestartCount       10 `
    -RestartInterval    (New-TimeSpan -Minutes 1) `
    -StartWhenAvailable `
    -MultipleInstances  IgnoreNew

# Roda como o usuario atual (tem Node no PATH e acesso a impressoras)
$currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
$principal   = New-ScheduledTaskPrincipal `
    -UserId   $currentUser `
    -LogonType Interactive `
    -RunLevel Highest

Register-ScheduledTask `
    -TaskName    $TaskName `
    -Description 'Fluxe POS local server: cash drawer ESC/POS + SMS automation' `
    -Action      $action `
    -Trigger     $trigger `
    -Settings    $settings `
    -Principal   $principal `
    -Force | Out-Null

Write-Host "  [OK] Tarefa '$TaskName' registrada para: $currentUser" -ForegroundColor Green

# ── 7. Iniciar servidor agora ─────────────────────────────────────────────────
Write-Host ""
Write-Host "  Iniciando servidor..." -ForegroundColor Yellow
Start-ScheduledTask -TaskName $TaskName
Start-Sleep -Seconds 3

# Health check
try {
    $resp = Invoke-WebRequest -Uri 'http://localhost:3001/api/health' -UseBasicParsing -TimeoutSec 5
    Write-Host "  [OK] Servidor rodando — http://localhost:3001" -ForegroundColor Green
} catch {
    Write-Host "  [..] Servidor iniciando — aguarde alguns segundos e acesse http://localhost:3001/api/health" -ForegroundColor Yellow
}

# ── Resumo ────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ============================================" -ForegroundColor Cyan
Write-Host "  Setup concluido com sucesso!" -ForegroundColor Cyan
Write-Host "  O servidor vai subir automaticamente em todo login do Windows." -ForegroundColor Cyan
Write-Host ""
Write-Host "  Porta:  http://localhost:3001" -ForegroundColor Gray
Write-Host "  Logs:   $LogFile" -ForegroundColor Gray
Write-Host "  Parar:  schtasks /end /tn FluxePOSServer" -ForegroundColor Gray
Write-Host "  Status: Get-ScheduledTask -TaskName FluxePOSServer" -ForegroundColor Gray
Write-Host "  ============================================" -ForegroundColor Cyan
Write-Host ""
Read-Host "  Pressione Enter para fechar"
